name: Conditions
on: push
jobs:
  # ワークフロー実行IDに「1」が含まれる場合のみシェルコマンドを実行するワークフロー
  skip-or-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '1') }} # ワークフロー実行IDで分岐
