name: Hello # ワークフロー名　
on: push # イベント　2.5節
jobs: # ジョブ　
  hello: # ジョブID
    runs-on: ubuntu-latest # ランナー(実行環境)　2.7節
    steps: # ステップ
      - run: | # シェルコマンド
          echo "Hello, world"
          git log -1
      - uses: actions/checkout@v4 # アクション　2.8節
