name: Manual
on:
  workflow_dispatch: # 手動実行
    inputs:
      greeting:
        # default: Hello
        # type: string
        type: choice
        options:
          - Hello
          - Hi
          - Hey
        required: true
        description: A Cheerful word
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.greeting }}
